# src/reasoning/report_generator.py
"""
Step 5: Generating the final report
"""

import requests
import os
from datetime import datetime
from .prompts import REPORT_SYNTHESIS_PROMPT, REPORT_SUMMARY_PROMPT

class ReasoningReportGenerator:
    """Generates the final structured report"""
    
    def __init__(self):
        self.api_key = os.getenv("OPENROUTER_API_KEY")
        self.model = os.getenv("OPENROUTER_MODEL", "openai/gpt-4o-mini")
    
    def _call_llm(self, prompt):
        """Appelle l'API OpenRouter"""
        try:
            response = requests.post(
                url="https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                    "HTTP-Referer": "http://localhost:3000",
                    "X-Title": "MITRE ATLAS Reasoning Engine"
                },
                json={
                    "model": self.model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.4,
                    "max_tokens": 1500
                },
                timeout=60
            )
            if response.status_code != 200:
                return None
            return response.json()['choices'][0]['message']['content']
        except:
            return None
    
    def generate(self, description, system_info, threats):
        """
        Generates the complete report
        
        Args:
            description: Original description
            system_info: System information
            threats: Prioritized threats
            
        Returns:
            str: Report in markdown
        """
        # Format the threats
        threats_str = self._format_threats(threats)
        
        # Generate the report
        prompt = REPORT_SYNTHESIS_PROMPT.format(
            description=description,
            system_info=str(system_info),
            threats=threats_str
        )
        
        report = self._call_llm(prompt)
        
        if not report:
            return self._generate_fallback(description, system_info, threats)
        
        # Add header and footer
        return self._wrap_report(report, description)
    
    def _format_threats(self, threats):
        """Format the threats for the prompt"""
        if not threats:
            return "No threats identified."
        
        lines = []
        for t in threats:
            lines.append(f"- {t.get('technique_name')} ({t.get('technique_id')})")
            lines.append(f"  - Severity: {t.get('severity', 'N/A')}")
            lines.append(f"  - CVSS: {t.get('cvss_score', 'N/A')}")
            lines.append(f"  - Mitigations: {', '.join(t.get('mitigations', ['None']))}")
            lines.append(f"  - Actors: {', '.join(t.get('actors', ['Unknown']))}")
            lines.append("")
        
        return "\n".join(lines)
    
    def _wrap_report(self, report, description):
        """Ajoute l'en-tête et le pied de page"""
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        header = f"""# 🛡️ Threat Assessment Report

**System Description:** {description[:100]}...

**Generated:** {date}

---
"""
        footer = """
---
*Report generated by MITRE ATLAS Reasoning Engine*
*All threats are grounded in the MITRE ATLAS knowledge graph*
*Citations reference MITRE ATLAS technique IDs*
"""
        return header + report + footer
    
    def _generate_fallback(self, description, system_info, threats):
        """Fallback report in case of LLM failure"""
        lines = []
        lines.append("# Threat Assessment Report (Fallback)")
        lines.append(f"\n**System:** {system_info.get('system_type', 'Unknown')}")
        lines.append(f"**Components:** {', '.join(system_info.get('components', ['Unknown']))}")
        lines.append("\n## Threats Found\n")
        
        if not threats:
            lines.append("No threats identified.")
        else:
            for t in threats[:10]:
                lines.append(f"### {t.get('technique_name')} ({t.get('technique_id')})")
                lines.append(f"- **Severity:** {t.get('severity', 'N/A')}")
                lines.append(f"- **Mitigations:** {', '.join(t.get('mitigations', ['None']))}")
                lines.append("")
        
        return "\n".join(lines)
    
    def generate_summary(self, report):
        """Generates an executive summary"""
        prompt = REPORT_SUMMARY_PROMPT.format(report=report)
        return self._call_llm(prompt) or "Executive summary unavailable."